apiVersion: policies.kubewarden.io/v1
kind: PolicyRevision
metadata:
  name: example-policyrevision
  namespace: default
spec:
  enabled: true
  data:
    module: "annotated-policy.wasm"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        operations:
          - CREATE
          - UPDATE
    settings:
      denied_labels:
        - foo
        - bar
